#! /bin/bash

# encodes $1 to mjpeg: $2
FILENAME=${1%.*}
FILEEXT="avi"
if [ $2 ]
then 
	NEWFILE=$2
else
	NEWFILE=${FILENAME}"."${FILEEXT}
fi

FILEPART=${NEWFILE}
COUNT=1
while [ -e $NEWFILE ]
do
	NEWFILE=${COUNT}"-"${FILEPART}
	((COUNT++))
done 

mencoder -o $NEWFILE -ovc lavc -lavcopts vcodec=mjpeg -nosound $1
