#! /bin/bash
# mknoise v0.1
# starts jackd and qjackctl (if not already running) and programs from a
# text file, each program in new line including options

# takes text file(s) as argument: $ ./mknoise file1 [file2 ...]
# e.g. ./mknoise mknoise-sample

if pgrep jackd
	then true 
	else /usr/bin/jackd -dalsa -r44100& > /dev/null 2>&1&
fi

if pgrep qjackctl  
	then true 
	else /usr/bin/qjackctl > /dev/null 2>&1&
fi

while [ "$1" ]; do
	cut -d " " -f 1 $1 >> .musicapplist 
	while read; do
		X="$REPLY"
		$X > /dev/null 2>&1&
	done < $1
	shift 
done
