#! /bin/bash
# stopnoise v0.1
# stops programs, that have been invoked by mknoise
# including jackd and qjackstl

# run with $ ./stopnoise

while read ; do
	X="$REPLY"
	killall $X
done <.musicapplist

rm .musicapplist

killall qjackctl
killall jackd
